"""multiple patient doctors

Revision ID: e13a010b0677
Revises: 1ac7a5831732
Create Date: 2018-06-23 15:34:40.150352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13a010b0677'
down_revision = '1ac7a5831732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('doctor', sa.Column('registration_number', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_doctor_registration_number'), 'doctor', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_registration_number'), table_name='doctor')
    op.drop_column('doctor', 'registration_number')
    op.drop_column('doctor', 'name')
    # ### end Alembic commands ###
