"""doctor table

Revision ID: ec40d60522ab
Revises: 
Create Date: 2018-06-17 07:51:17.558970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec40d60522ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_username'), 'doctor', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_username'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
